=>v0.5
- Dodano ustawienia launchera(zębatka obok kontrolki minimalizacji), dzięki temu możesz skonfigurować go pod siebie.
- Naprawiono błąd z wyskakującym oknem 'Błąd skryptu'(Niektórym osobom się taki błąd pokazuje).
- Naprawiono błąd ze znikaniem wskaźnika pisania na czacie podczas gdy czat się odświeżał.
- Dodano obsługę radia PTG(w ustawieniach) - teraz uruchamiając launcher od razu możemy słuchać radia PTG :). (I tu uwaga! Aby radio działało, aplikacja w swoim katalogu musi mieć plik bass.dll w wersji 2.4.10 - taki plik znajduje sie w katalogu GTA, tak więc wystarczy aby aplikacja po prostu była w katalogu GTA)
=>0.6
- Naprawiono błędy autostartu.
- Aplikację da się już uruchomić bez pliku bass.dll - kosztuje nas to brakiem funkcji radia. 
- Możliwość zablokowania próby ładowania pliku bass.dll - wystarczy stworzyć w katalogu aplikacji nowy folder o nazwie 'unusebass'.
- Dodano kolejną łatkę jeśli chodzi o znikanie kursora pisania na czacie.(Wymaga testów)
- Regulator głośności radia jest teraz jeszcze bardziej precyzyjny - Zalecam ustawienie na nowo głośności radia, gdyż stare ustawienia spowodują, że radio bedzie grało cicho.
- Wylogowanie z launchera nie wyłącza go - wyświetla się okienko logowania.
- Przycisk uruchom gre jest nieaktywny do póki Launcher nie załaduje wszystkich statystyk.
- Małe poprawki do autologwania na serwer(błąd err_11).
- Zoptymalizowano ładowanie statystyk.
=>1.0 PRO
- Wznowiono oficjalne wsparcie dla aplikacji (będę ją nadal rozwijał).
- [HIT!]Wsparcie SA:MP+ (nowe funkcje dostępne w SA:MP!!!). 
- Przy ładowaniu gry, widzimy logo PTG.
- Zmodernizowano ustawienia [zakładki].
- Tryb TURBO.
- Dodano eksperymentalną metodę rozruchu GTA - SA:MP ASI Load. (Standardowa to wstrzykiwanie biblioteki sampa bezpośrednio do procesu gry)
- Możliwość zmiany radia na inne.
- Na stronie statystyk wyswietlana jest tytuł piosenki lecącej w radiu.
-